package language

// General Symbols
var (
	Newline          *Symbol = NewSymbol("\n")
	CarridgeReturn   *Symbol = NewSymbol("\r")
	Tab              *Symbol = NewSymbol("\t")
	DoubleQuote      *Symbol = NewSymbol("\"")
	SingleQuote      *Symbol = NewSymbol("'")
	OpenBracket      *Symbol = NewSymbol("(")
	CloseBracket     *Symbol = NewSymbol(")")
	SquareQuoteOpen  *Symbol = NewSymbol("[")
	SquareQuoteClose *Symbol = NewSymbol("]")
	WildcardBlank    *Symbol = NewSymbol("{{blank}}")
	Blank            *Symbol = NewSymbol("-")
	Degree           *Symbol = NewSymbol("°")
	Break            *Symbol = NewSymbol(" ━━ ")
	Space            *Symbol = NewSymbol(" ")
	PromptSymbol     *Symbol = NewSymbol("? ")
	Truncate         *Symbol = NewSymbol("...")
)
var (
	// Actions
	Yes         *Action = NewAction("Y")
	No          *Action = NewAction("N")
	Quit        *Action = NewAction("Q")
	Forward     *Action = NewAction("F")
	Back        *Action = NewAction("B")
	Exit        *Action = NewAction("EX")
	Help        *Action = NewAction("?") // Help
	Up          *Action = NewAction("U")
	UpDoubleDot *Action = NewAction("..")
	UpArrow     *Action = NewAction("^")
	Go          *Action = NewAction("G")
	Select      *Action = NewAction("S")
)

const (
// SymSingleQuote      string = "'"
// SymOpenBracket      string = "("
// SymCloseBracket     string = ")"
// SymSquareQuoteOpen  string = "["
// SymSquareQuoteClose string = "]"
// SymActionYes        string = "Y"
// SymActionNo         string = "N"
// SymBlank            string = "-"
// SymDegree           string = "°"
// SymBreak            string = " ━━ "
// Space               string = " "
// SymPromptSymbol     string = "? "
// SymActionQuit       string = "Q"
// SymActionForward    string = "F"
// SymActionBack       string = "B"
// SymActionExit       string = "EX"
// SymTruncate         string = "..."
// SymActionHelp       string = "?" // Help
// SymWildcardBlank    string = "{{blank}}"
)

// Page - Paging
const TxtPagingPrompt string = "Choose (F)orward, (B)ack or (Q)uit"

// Support DatesTimes
var (
	OneWord            *Text = NewText("one")
	OneNumeric         *Text = NewText("1")
	Minutes            *Text = NewText("minutes")
	MinutesShort       *Text = NewText("mins")
	Hour               *Text = NewText("hour")
	HourShort          *Text = NewText("hr")
	MillisecondsShort  *Text = NewText("ms")
	ApplicationVersion *Text = NewText("StarTerm - Utilities 1.0 %s")
	ApplicationName    *Text = NewText("StarTerm")
	Error              *Text = NewText("ERROR ")
	Info               *Text = NewText("INFO ")
	Warning            *Text = NewText("WARNING ")
	Success            *Text = NewText("SUCCESS ")
	Hint               *Text = NewText("HINT ")
	Paging             *Text = NewText("Page %v of %v")
	MinMax             *Text = NewText("Min: %v Max: %v")
	ValidActions       *Text = NewText("valid actions [%v]")
)

var ApplicationHeader []string = []string{
	"███████ ████████  █████  ██████  ████████ ███████ ██████  ███    ███ ",
	"██         ██    ██   ██ ██   ██    ██    ██      ██   ██ ████  ████ ",
	"███████    ██    ███████ ██████     ██    █████   ██████  ██ ████ ██ ",
	"     ██    ██    ██   ██ ██   ██    ██    ██      ██   ██ ██  ██  ██ ",
	"███████    ██    ██   ██ ██   ██    ██    ███████ ██   ██ ██      ██ ",
}

// General
var (
	TableCharacterUnderline *Text = NewText("-")
	TextLineConstructor     *Text = NewText("%s%s%s")
	MACAddressConstructor   *Text = NewText("%v:%v:%v:%v:%v:%v")
	IPAddressConstructor    *Text = NewText("%v.%v.%v.%v")
	TxtMinMaxLength         *Text = NewText("Text Length Min: %v Max: %v")
	TxtProceed              *Text = NewText("Proceed")
	TxtSetPrompt            *Text = NewText("Please set a prompt for the page")
)

// FileChooser
var (
	TxtFileChooserTitle *Text = NewText("File Chooser")
	TxtFolderIcon       *Text = NewText("+")
	TxtFileIcon         *Text = NewText("#")
	TxtSymLinkIcon      *Text = NewText("~")
	//TODO: Convert to *Paragaph
	TxtFileChooserDescription  []string = []string{"This menu shows the list of files available for maintenance.", "Select the file you wish to use. PLEASE BE CAREFUL!"}
	TxtFileChooserPrompt       *Text    = NewText("Choose a file to use")
	TxtFileChooserConfirmation *Text    = NewText("Choose (S)end or (Q)uit")
)

// Help Messages
var (
	HelpPageTitle        *Text = NewText("Help Page")
	HelpFor              *Text = NewText("Help for ")
	HelpPromptSinglePage *Text = NewText("Choose (Y)es when done")
	HelpPromptMultiPage  *Text = NewText("Choose (F)orward, (B)ack or (Y)es when done")
	HelpSupportedActions *Text = NewText("The following actions are supported:")
	HelpAutoGenerated    *Text = NewText("Autogenerated : ")
	HelpBullet           *Text = NewText("- ")
	HelpHint             *Text = NewText("Help:")
)
